version: '3.5'

services:
    auth-app:
        container_name: auth-app
        image: auth-app
        build:
            context: .
            dockerfile: .deploy/Dockerfile
            target: AUTH
        restart: 'no'
        ports:
            - '4200:4200'

    client-app:
        container_name: client-app
        image: client-app
        build:
            context: .
            dockerfile: .deploy/Dockerfile
            target: CLIENT
        volumes:
            - .deploy/config/nginx.conf:/etc/nginx/conf.d/default.conf
        restart: 'no'
        ports:
            - '4201:80'

    agency-app:
        container_name: agency-app
        image: agency-app
        build:
            context: .
            dockerfile: .deploy/Dockerfile
            target: AGENCY
        volumes:
            - .deploy/config/nginx.conf:/etc/nginx/conf.d/default.conf
        restart: 'no'
        ports:
            - '4202:80'

    # curator-app:
    #   container_name: curator-app
    #   image: curator-app
    #   build:
    #     context: .
    #     dockerfile: .deploy/Dockerfile
    #     target: CURATOR
    #   volumes:
    #     - .deploy/config/nginx.conf:/etc/nginx/conf.d/default.conf
    #   restart: "no"
    #   ports:
    #     - "4203:80"
