import { concatStrings } from './lib/help-functions/concatStrings';
import { getSessionCookie } from './lib/storage-service/getSession';
import { logout, resetAuth } from './lib/services-setting/logout';
import { setAuthTokens } from './lib/services-setting/setAuth';

export { logout, concatStrings, resetAuth, setAuthTokens, getSessionCookie };

export * from './lib/sentryLogging/initializeErrorLogging';
export * from './lib/error-handling/responseMessagesTransformer';
export * from './lib/error-handling/linksByErrorsKeyPhrases';
export * from './lib/error-handling/validationErrorMessages';
export * from './lib/error-handling/stripeErrorHandler';
export * from './lib/error-handling/defaultErrorHandler';
export * from './lib/error-handling/getErrorMessageForSchema';
export * from './lib/help-functions/stringTransformFunctions';
export * from './lib/help-functions/modifyHandleChangeField';
export * from './lib/help-functions/getPromiseImage';
export * from './lib/services-setting/baseQuery';
export * from './lib/services-setting/fotmattedToken';
export * from './lib/pattern-validation/regexpForm';
export * from './lib/services-setting/baseApi';
export * from './lib/storage-service/cookie';
export * from './lib/storage-service/storageController';
export * from './lib/internal-redirect/redirect';
export * from './lib/internal-redirect/checkPageLoadCorrect';
export * from './lib/pattern-text/regExpText';
export * from './lib/format-text/formatText';
export * from './lib/formatLinks/formatSociallinks';
export * from './lib/mask-phone-number/maskForPhoneNumber';
export * from './lib/adapters/sharingAdapters';
export * from './lib/adapters/getDataByProjectScope';
export * from './lib/help-functions/isEstimateExceedingBudget';
export * from './lib/scroll-functions/scrollAboveKeyboard';

export * from './lib/adapters/getTransformCase';

export * from './lib/formatBrandDocuments/formatBrandDocumentsIcon';

export * from './lib/payments-functions/validationPayments';
export * from './lib/payments-functions/calculatePayments';
export * from './lib/parser-url/getUrlParam';
export * from './lib/parser-url/getDomain';
export * from './lib/listIcon/getIconPayment';
export * from './lib/animation/animationSettings';
export * from './lib/help-functions/getLinkDownloadContracts';
export * from './lib/help-functions/checkIsElemOverflowsOnElement';
export * from './lib/moment-locale-setting/localeSetting';
export * from './lib/formatLinks/replaceSocialLink';
export * from './lib/dateTransformers/dateUtcTransformer';
export * from './lib/help-functions/getHostName';
export * from './lib/help-functions/getClasses';
export * from './lib/help-functions/getCurrentYear';
export * from './lib/help-functions/checksPhoneNumber';
export * from './lib/help-functions/getBrandLinks';
export * from './lib/help-functions/getFiles';
export * from './lib/help-functions/updateLinksArray';
export * from './lib/help-functions/concatStrings';
export * from './lib/help-functions/simulationLinkClick';
export * from './lib/help-functions/checkContainsLink';
export * from './lib/help-functions/getIs404StatusCode';
export * from './lib/help-functions/getIs500StatusCode';
export * from './lib/help-functions/getProjectTitle';

export * from './lib/googleAnalytics/setEvents';
export * from './lib/phone-number-transformers/parsePhoneNumberToObj';
export * from './lib/configs/marketingScreenConfig';
export * from './lib/configs/ourFeatureScreen';
export * from './lib/initialStatesShared/projectInfoInitialState';
export * from './lib/help-functions/sortFunctions';
export * from './lib/mocks/mockProjectData';
export * from './lib/mocks/mockActions';
export * from './lib/enumFunctions';
export * from './lib/mocks/mockPitchData';
export * from './lib/schemas';
export * from './lib/autocomplete/transformGoogleResult';
export * from './lib/sentryLogging/sendErrorToSentry';
export * from './lib/file-upload-functions/getAcceptFileTypes';
export * from './lib/file-upload-functions/getErrorUploadMessage';
