version: '3.7'

networks:
    breef_test:
        name: breef-test-$CI_PIPELINE_ID
        driver: bridge

services:
    auth-web-app:
        container_name: breef-auth-web-$CI_PIPELINE_ID
        image: $AUTH_COMMIT_IMAGE
        networks:
            breef_test:
                aliases:
                    - breef.autotests
        depends_on:
            breef-backend:
                condition: service_healthy
        healthcheck:
            test: curl --fail http://localhost:80 || exit 1
            interval: 60s
            retries: 5
            start_period: 30s
            timeout: 10s

    client-web-app:
        container_name: breef-client-web-$CI_PIPELINE_ID
        image: $CLIENT_COMMIT_IMAGE
        command: start_client
        networks:
            breef_test:
                aliases:
                    - client.breef.autotests
        depends_on:
            breef-backend:
                condition: service_healthy
        healthcheck:
            test: curl --fail http://localhost:4201 || exit 1
            interval: 60s
            retries: 5
            start_period: 30s
            timeout: 10s

    agency-web-app:
        container_name: breef-agency-web-$CI_PIPELINE_ID
        image: $AGENCY_COMMIT_IMAGE
        command: start_agency
        networks:
            breef_test:
                aliases:
                    - agency.breef.autotests
        depends_on:
            breef-backend:
                condition: service_healthy
        healthcheck:
            test: curl --fail http://localhost:4202 || exit 1
            interval: 60s
            retries: 5
            start_period: 30s
            timeout: 10s

    # curator-web-app:
    #   container_name: breef-curator-web-$CI_PIPELINE_ID
    #   image: $CURATOR_COMMIT_IMAGE
    #   networks:
    #     - breef_test
    #   depends_on:
    #     breef-backend:
    #       condition: service_healthy
