export type TipOfDayType = {
    id: number;
    header: string;
    copy: string;
    signOff: string;
    isEmoji: boolean;
};

export const getTipOfDayNext = (tipId: string, tips: TipOfDayType[]) => {
    const tipIndex = tips.findIndex(tip => tip.id === Number(tipId));
    if (tipIndex === tips.length - 1) {
        return tips[0];
    }
    return tips[tipIndex + 1];
};

export const getTipOfDayRandom = (tips: TipOfDayType[]) => {
    return tips[Math.floor(Math.random() * tips.length)];
};

export const tipsOfDayClient: TipOfDayType[] = [
    {
        id: 1,
        header: 'Did you know…',
        copy: 'We have 10K+ vetted agencies (and growing!) in our agency community!',
        signOff: '🌎',
        isEmoji: true,
    },
    {
        id: 2,
        header: 'Fun Fact:',
        copy: 'Our co-founder was a marketer (and hated the pains of finding an agency).',
        signOff: '🤠',
        isEmoji: true,
    },
    {
        id: 3,
        header: 'Did you know…',
        copy: 'You can do over 50 types of marketing projects with agencies on Breef!',
        signOff: '🤯',
        isEmoji: true,
    },
    {
        id: 4,
        header: 'Did you know…',
        copy: 'You can easily manage all agency payments + contracts on Breef.',
        signOff: '💸',
        isEmoji: true,
    },
    {
        id: 5,
        header: 'Fun Fact:',
        copy: 'Emails with emojis in the subject line increase open rates by 56%.',
        signOff: '(Visual Oak Marketing)',
        isEmoji: false,
    },
    {
        id: 6,
        header: 'Fun Fact:',
        copy: '46% of consumers want to watch product videos before they buy.',
        signOff: '(Shopify)',
        isEmoji: false,
    },
    {
        id: 7,
        header: 'Did you know…',
        copy: 'Your Brand Lead can help you plan, scope, + budget projects. They’ve seen it all.',
        signOff: '🙌',
        isEmoji: true,
    },
    {
        id: 8,
        header: 'Ponder This...',
        copy: 'Does your content lead readers on a journey, or does it merely stuff them as leads into a pipeline?',
        signOff: '- Ann Handley',
        isEmoji: false,
    },
    {
        id: 9,
        header: 'Good Words:',
        copy: 'Content builds relationships. Relationships are built on trust. Trust drives revenue.',
        signOff: '- Andrew Davis',
        isEmoji: false,
    },
    {
        id: 10,
        header: 'Did you know…',
        copy: 'Most of #TeamBreef were marketers, founders, or agency folks. We’ve been in your shoes!',
        signOff: '😎',
        isEmoji: true,
    },
    {
        id: 11,
        header: 'Fun Fact:',
        copy: '50% of active U.S. TikTok users said they bought an item after seeing it reviewed on the app.',
        signOff: '(Adweek)',
        isEmoji: false,
    },
    {
        id: 12,
        header: 'Ponder This...',
        copy: 'Content marketing is a commitment, not a campaign.',
        signOff: '- Jon Buscall',
        isEmoji: false,
    },
    {
        id: 13,
        header: 'Did you know…',
        copy: "Once you post a project, you’ll get pitches in < 7 days (vs. 3+ months the 'old way').",
        signOff: '🙌',
        isEmoji: true,
    },
    {
        id: 14,
        header: 'Fun Fact:',
        copy: '89% of marketers believe specialization will drive the future of work.',
        signOff: '(Breef Insights)',
        isEmoji: false,
    },
    {
        id: 15,
        header: 'Good Words:',
        copy: 'People don’t buy what you do, they buy why you do it.',
        signOff: '- Simon Sinek',
        isEmoji: false,
    },
    {
        id: 16,
        header: 'Fun Fact:',
        copy: '80% of marketers who leverage audio content + podcasts plan to invest the same amount or more budget next year.',
        signOff: '(Hubspot)',
        isEmoji: false,
    },
    {
        id: 17,
        header: 'Good Words:',
        copy: 'You can’t sell anything if you can’t tell anything.',
        signOff: '- Beth Comstock',
        isEmoji: false,
    },
    {
        id: 18,
        header: 'Did you know…',
        copy: 'You can loop in your colleagues for pitch reviews, agency intros, & payments.',
        signOff: '🤝',
        isEmoji: true,
    },
    {
        id: 19,
        header: 'Ponder This...',
        copy: 'Focus on being productive instead of being busy.',
        signOff: '- Tim Ferris',
        isEmoji: false,
    },
    {
        id: 20,
        header: 'Good Words:',
        copy: 'Google only loves you when everyone else loves you first.',
        signOff: '- Wendy Piersall',
        isEmoji: false,
    },
    {
        id: 21,
        header: 'Did you know…',
        copy: 'We work within budget ranges for transparent pricing.',
        signOff: '💸',
        isEmoji: true,
    },
    {
        id: 22,
        header: 'Did you know…',
        copy: 'We have templates for our most popular projects. Just click to post!',
        signOff: '🤌',
        isEmoji: true,
    },
    {
        id: 23,
        header: 'Good Words:',
        copy: 'Design like you are absolutely right, then optimize like you were wrong from the start.',
        signOff: '- Jordie van Rijn',
        isEmoji: false,
    },
    {
        id: 24,
        header: 'Fun Fact:',
        copy: '30% of email recipients open email based on the subject line alone.',
        signOff: '(Milkwhale Digital)',
        isEmoji: false,
    },
    {
        id: 25,
        header: 'Did you know…',
        copy: 'On average, you’ll receive 5-6 pitches from agencies vetted for your project.',
        signOff: '✨',
        isEmoji: true,
    },
    {
        id: 26,
        header: 'Did you know…',
        copy: 'Our community is home to agencies in over 20 countries!',
        signOff: '🌎',
        isEmoji: true,
    },
    {
        id: 27,
        header: 'Good Words:',
        copy: "Authenticity is not a strategy, it's mandatory.",
        signOff: '- Kate Santore',
        isEmoji: false,
    },
    {
        id: 28,
        header: 'Did you know...',
        copy: 'It only costs $99 to post a project on Breef (saving you $ + search time).',
        signOff: '💯',
        isEmoji: true,
    },
    {
        id: 29,
        header: 'Good Words:',
        copy: 'Either write something worth reading or do something worth writing about.',
        signOff: '- Benjamin Franklin',
        isEmoji: false,
    },
    {
        id: 30,
        header: 'Did you know...',
        copy: 'Our platform encourages competitive (and transparent) agency pricing!',
        signOff: '🙌',
        isEmoji: true,
    },
    {
        id: 31,
        header: 'Good Words:',
        copy: "It's better to fail in originality than to succeed in imitation.",
        signOff: '- Herman Melville',
        isEmoji: false,
    },
    {
        id: 32,
        header: 'Fun Fact:',
        copy: 'It takes ~0.05 seconds for consumers to form an opinion about your website.',
        signOff: '(8ways)',
        isEmoji: false,
    },
    {
        id: 33,
        header: 'Ponder This...',
        copy: 'Good ads get consumers to stop and stare. Effective ads inspire engagement.',
        signOff: '(HubSpot)',
        isEmoji: false,
    },
    {
        id: 34,
        header: 'Ponder This...',
        copy: 'The most clever and effective ads are sometimes the most subtle.',
        signOff: '(Forbes)',
        isEmoji: false,
    },
];

export const tipsOfDayAgency: TipOfDayType[] = [
    {
        id: 1,
        header: 'Did you know…',
        copy: 'Our co-founder once prepped a client deck until 2am. That why a Breef Pitch takes < 15 min!',
        signOff: '💃',
        isEmoji: true,
    },
    {
        id: 2,
        header: 'Fun Fact:',
        copy: '86% of agencies added a new service offering in the last year.',
        signOff: '(Search Engine Journal)',
        isEmoji: false,
    },
    {
        id: 3,
        header: 'Did you know…',
        copy: 'You can upload gifs to a Breef Pitch to add a personal touch.',
        signOff: '🤠',
        isEmoji: true,
    },
    {
        id: 4,
        header: 'Did you know…',
        copy: 'Our team has been in your shoes! Most have worked at (or founded) small agencies.',
        signOff: '🤝',
        isEmoji: true,
    },
    {
        id: 5,
        header: 'Fun Fact:',
        copy: 'Emails with emojis in the subject line increase open rates by 56%.',
        signOff: '(Visual Oak Marketing)',
        isEmoji: false,
    },
    {
        id: 6,
        header: 'Fun Fact:',
        copy: '46% of consumers want to watch product videos before they buy.',
        signOff: '(Shopify)',
        isEmoji: false,
    },
    {
        id: 7,
        header: 'Did you know…',
        copy: 'Our agency community spans over 20 countries!',
        signOff: '🌎',
        isEmoji: true,
    },
    {
        id: 8,
        header: 'Ponder This...',
        copy: 'Does your content lead readers on a journey, or does it merely stuff them as leads into a pipeline?',
        signOff: '- Ann Handley',
        isEmoji: false,
    },
    {
        id: 9,
        header: 'Good Words:',
        copy: 'Content builds relationships. Relationships are built on trust. Trust drives revenue.',
        signOff: '- Andrew Davis',
        isEmoji: false,
    },
    {
        id: 10,
        header: 'Did you know…',
        copy: 'All project opportunities are vetted for your agency + expertise!',
        signOff: '🙌',
        isEmoji: true,
    },
    {
        id: 11,
        header: 'Fun Fact:',
        copy: '50% of active U.S. TikTok users said they bought an item after seeing it reviewed on the app.',
        signOff: '(Adweek)',
        isEmoji: false,
    },
    {
        id: 12,
        header: 'Ponder This...',
        copy: 'Content marketing is a commitment, not a campaign.',
        signOff: '- Jon Buscall',
        isEmoji: false,
    },
    {
        id: 13,
        header: 'Did you know…',
        copy: 'We host monthly agency webinars! Email community@breef.com for more info.',
        signOff: '💻',
        isEmoji: true,
    },
    {
        id: 14,
        header: 'Fun Fact:',
        copy: '89% of marketers believe specialization will drive the future of work.',
        signOff: '(Breef Insights)',
        isEmoji: false,
    },
    {
        id: 15,
        header: 'Good Words:',
        copy: 'People don’t buy what you do, they buy why you do it.',
        signOff: '- Simon Sinek',
        isEmoji: false,
    },
    {
        id: 16,
        header: 'Fun Fact:',
        copy: '80% of marketers who leverage audio content + podcasts plan to invest the same amount or more budget next year.',
        signOff: '(Hubspot)',
        isEmoji: false,
    },
    {
        id: 17,
        header: 'Good Words:',
        copy: 'You can’t sell anything if you can’t tell anything.',
        signOff: '- Beth Comstock',
        isEmoji: false,
    },
    {
        id: 18,
        header: 'Did you know…',
        copy: 'If you are shortlisted by a client, we’ll arrange intro calls ASAP.',
        signOff: '',
        isEmoji: false,
    },
    {
        id: 19,
        header: 'Ponder This...',
        copy: 'Focus on being productive instead of being busy.',
        signOff: '- Tim Ferris',
        isEmoji: false,
    },
    {
        id: 20,
        header: 'Good Words:',
        copy: 'Google only loves you when everyone else loves you first.',
        signOff: '- Wendy Piersall',
        isEmoji: false,
    },
    {
        id: 21,
        header: 'Did you know…',
        copy: 'You can upload your agency deck or case studies to a Breef Pitch.',
        signOff: '💯',
        isEmoji: true,
    },
    {
        id: 22,
        header: 'Did you know…',
        copy: 'All payments are managed on Breef — you’ll get paid quickly + securely.',
        signOff: '💸',
        isEmoji: true,
    },
    {
        id: 23,
        header: 'Good Words:',
        copy: 'Design like you are absolutely right, then optimize like you were wrong from the start.',
        signOff: '- Jordie van Rijn',
        isEmoji: false,
    },
    {
        id: 24,
        header: 'Fun Fact:',
        copy: '30% of email recipients open email based on the subject line alone.',
        signOff: '(Milkwhale Digital)',
        isEmoji: false,
    },
    {
        id: 25,
        header: 'Did you know…',
        copy: 'All project opportunities are vetted for your agency + expertise!',
        signOff: '🤠',
        isEmoji: true,
    },
    {
        id: 26,
        header: 'Did you know…',
        copy: 'You can invite members of your team to help with pitching + payments.',
        signOff: '👌',
        isEmoji: true,
    },
    {
        id: 27,
        header: 'Good Words:',
        copy: "Authenticity is not a strategy, it's mandatory.",
        signOff: '- Kate Santore',
        isEmoji: false,
    },
    {
        id: 28,
        header: 'Did you know...',
        copy: 'We have an Agency Team who will help answer any + all questions. Say hi at community@breef.com.',
        signOff: '🤌',
        isEmoji: true,
    },
    {
        id: 29,
        header: 'Good Words:',
        copy: 'Either write something worth reading or do something worth writing about.',
        signOff: '- Benjamin Franklin',
        isEmoji: false,
    },
    {
        id: 30,
        header: 'Did you know...',
        copy: 'A Breef Pitch includes a spot for your values - so everyone is on the same page.',
        signOff: '👌',
        isEmoji: true,
    },
    {
        id: 31,
        header: 'Good Words:',
        copy: "It's better to fail in originality than to succeed in imitation.",
        signOff: '- Herman Melville',
        isEmoji: false,
    },
    {
        id: 32,
        header: 'Fun Fact:',
        copy: 'It takes ~0.05 seconds for consumers to form an opinion about your website.',
        signOff: '(8ways)',
        isEmoji: false,
    },
    {
        id: 33,
        header: 'Ponder This...',
        copy: 'Good ads get consumers to stop and stare. Effective ads inspire engagement.',
        signOff: '(HubSpot)',
        isEmoji: false,
    },
    {
        id: 34,
        header: 'Ponder This...',
        copy: 'The most clever and effective ads are sometimes the most subtle.',
        signOff: '(Forbes)',
        isEmoji: false,
    },
];
